spring.application.name=EiMT
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/eimt_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.flyway.locations=classpath:db/migration
springfox.documentation.swagger-ui.enabled=true
server.port=8080